apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        runAsUser: 472
        runAsGroup: 472
        fsGroup: 472
      containers:
      - name: grafana
        image: grafana/grafana:11.0.0
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: storage
          mountPath: /var/lib/grafana
        - name: grafana-dashboards
          mountPath: /var/lib/grafana/dashboards
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboard-provider
          mountPath: /etc/grafana/provisioning/dashboards
        env:
        - name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_UID
          value: msqzbWjWk
        - name: GF_SERVER_ROOT_URL
          value: http://grafana-service.monitoring.svc.cluster.local:3000/grafana
        - name: GF_SERVER_SERVE_FROM_SUB_PATH
          value: "true"
        - name: GF_ANALYTICS_CHECK_FOR_UPDATES
          value: "true"
        - name: GF_USERS_DEFAULT_THEME
          value: light
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: "false"
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: grafana-pvc
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
      - name: grafana-dashboard-provider
        configMap:
          name: grafana-dashboard-provider
