apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |-
    [server]
    root_url = http://localhost:3000/grafana
    serve_from_sub_path = true
    [analytics]
    check_for_updates = true
    [users]
    default_theme = light
    [auth]
    disable_login_form = false
    [dashboards]
    default_home_dashboard_uid = mF5EwopGz
